drop table if exists string_model;

create table string_model
(
    str_id integer generated by default as identity primary key,
    str    varchar(100) not null
);


insert into string_model(str) values ('aaa'),('bbb');